"""
Learn about exceptions
when an exception is found, normal flow of program is interrupted

"""




def main():
    """
    test function
    :return: none
    """



    print("Done")






if __name__ == '__main__':
    main()
    exit(0)
